version: "3.8"

services:
  # Serviço PostgreSQL
  postgres:
    image: postgres:14.13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cb8c87193f183f91a16e6eb697ca84ec  # Altere para uma senha segura
    ports:
      - "5432:5432"  # Porta padrão do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados
    networks:
      - rede_geral
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "0.5"

volumes:
  postgres_data:
    external: false
    name: postgres_data

networks:
  rede_geral:
    external: false
    name: rede_geral
